// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA90jXKPsLHelo5B9qM6OUJUpTNNiX7llE',
    appId: '1:144899915965:web:70f17c17212f8c176877d4',
    messagingSenderId: '144899915965',
    projectId: 'fir-auth-c1946',
    authDomain: 'fir-auth-c1946.firebaseapp.com',
    storageBucket: 'fir-auth-c1946.firebasestorage.app',
    measurementId: 'G-C5BZSXDM0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrunnhsjwiHb-JrJAkg0zodhHSiPN_uoI',
    appId: '1:144899915965:android:dc3d4a42dd91eee06877d4',
    messagingSenderId: '144899915965',
    projectId: 'fir-auth-c1946',
    storageBucket: 'fir-auth-c1946.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6bFg0CC6OklbfOGWJT_byyX8BVP2z7zk',
    appId: '1:144899915965:ios:e4cbc2ee84d9ac126877d4',
    messagingSenderId: '144899915965',
    projectId: 'fir-auth-c1946',
    storageBucket: 'fir-auth-c1946.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6bFg0CC6OklbfOGWJT_byyX8BVP2z7zk',
    appId: '1:144899915965:ios:e4cbc2ee84d9ac126877d4',
    messagingSenderId: '144899915965',
    projectId: 'fir-auth-c1946',
    storageBucket: 'fir-auth-c1946.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA90jXKPsLHelo5B9qM6OUJUpTNNiX7llE',
    appId: '1:144899915965:web:804849046d9ce7ae6877d4',
    messagingSenderId: '144899915965',
    projectId: 'fir-auth-c1946',
    authDomain: 'fir-auth-c1946.firebaseapp.com',
    storageBucket: 'fir-auth-c1946.firebasestorage.app',
    measurementId: 'G-6JV0E3SF27',
  );
}
